### ISSUE TITLE
Problem with touch buttons on KP3S

### ISSUE THREAD

**Issue by nehilo** [gouache/Marlin-Configurations#1]
Thank to you for you great work!
I have problem with touch buttons on lcd. They are dont showing(

**Comment by gouache** [comment]
I patched this file again following the latest Marlin code.
pls try again

https://github.com/gouache/Marlin-Configurations/blob/master/Kingroon/KP3S/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO.h

2020년 8월 23일 (일) 오후 6:01, nehilo <notifications@github.com>님이 작성:

**Comment by nehilo** [comment]
Yes. Thats code is working!Thank to you a lot!!
